from . import product_template
from . import td_warranty_period
from . import td_warranty_record
from . import account_move
from . import stock_picking
from . import sale_order
from . import sale_order_line
from . import stock_lot
from . import res_partner
