{
    "name": "Agreement",
    "version": "18.0.1.2.0",
    "summary": "Agreement",
    "description": "",
    "author": "ToDo",
    "website": "todo.ltd",
    "images": [
        "static/description/banner.png",
    ],
    "depends": [
        "account_accountant",
        "account_reports",
        "contacts",
        "mail",
        "purchase",
        "sale_management",
    ],
    "data": [
        "data/ir_cron.xml",
        "security/ir.model.access.csv",
        "views/agreement_menu.xml",
        "views/agreement_views.xml",
        "views/sale_order_views.xml",
        "views/td_agreement_types_views.xml",
        "views/purchase_order_views.xml",
        "views/account_move_views.xml",
        "views/account_payment_views.xml",
        "views/account_move_line_views.xml",
    ],
    "demo": [],
    "assets": {"web.assets_backend": ["td_agreement/static/src/components/**/*"]},
    "installable": True,
    "application": True,
    "license": "OPL-1",
}
