from . import td_manufacturer_directory
from . import td_one_c_category
from . import product_template
from . import stock_warehouse
from . import td_tax_invoice
from . import td_tax_invoice_line
from . import account_move
from . import sale_order
from . import sale_order_line
from . import account_move_line
from . import stock_picking
from . import purchase_order
from . import stock_move
from . import stock_picking_type
from . import res_partner
